### ISSUE TITLE
USE LENSES!!!!

### ISSUE THREAD

**Issue by LiuTaowen-Tony** [sorrowfulT-Rex/Haskell-RecordBuilder#1]
Lens is a lib for that! Stop reinventing the wheel [doge]

**Comment by sorrowfulT-Rex** [comment]
1. This repo serves as a completely different model from "lens" as the latter is a lame attempt at rectifying a paraplegic design of record accessing in Haskell.
2. Unless you find a behavioural anomaly in this repo, please do not open "issues" as if it is your Iranian backyard of the U.S. 
3. "I consider this as bullying and reserve my right for legal actions." -- A certain respected teacher from a reputable university.
